# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fcfe3e076dde36032dc993a5259630bb2f0f23eeedbead6d6be4dbdddd3dac1977ebed732fad67ff36064843daf8e525c10cff2ee2f357fe8ba0e2887643fc

test:
  secret_key_base: b873f74144ac773e3716ef8f828196674f9f70e24d4d772d4a5947baf29524ad822dafff45c22988ede34af00ed681ead8557e34332d5b061692293e2910787c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
